addSbtPlugin("org.foundweekends.conscript" % "sbt-conscript" % "0.5.9")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.5")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.3.1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.12.0")
addSbtPlugin("com.github.sbt" % "sbt-release" % "1.4.0")
